// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using auth_server.Repositories;

namespace auth_server.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200712141834_EmailAsKeyOrgs")]
    partial class EmailAsKeyOrgs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("auth_server.Models.CountryModels.Country", b =>
                {
                    b.Property<string>("_name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("_name");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("auth_server.Models.OrganizationModels.Organization", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("salt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("email");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("auth_server.Models.UserTemplateModels.UserTemplate", b =>
                {
                    b.Property<Guid>("_tid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("organizationemail")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("_tid");

                    b.HasIndex("organizationemail");

                    b.ToTable("UserTemplates");
                });

            modelBuilder.Entity("auth_server.Models.CountryModels.Country", b =>
                {
                    b.OwnsMany("auth_server.Models.CountryModels.State", "states", b1 =>
                        {
                            b1.Property<string>("Country_name")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("name")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Country_name", "Id");

                            b1.ToTable("State");

                            b1.WithOwner()
                                .HasForeignKey("Country_name");
                        });
                });

            modelBuilder.Entity("auth_server.Models.UserTemplateModels.UserTemplate", b =>
                {
                    b.HasOne("auth_server.Models.OrganizationModels.Organization", "organization")
                        .WithMany("_templates")
                        .HasForeignKey("organizationemail");

                    b.OwnsMany("auth_server.Models.UserTemplateModels.UserTemplateAttribute", "attributes", b1 =>
                        {
                            b1.Property<Guid>("UserTemplate_tid")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("name")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("type")
                                .HasColumnType("int");

                            b1.HasKey("UserTemplate_tid", "Id");

                            b1.ToTable("UserTemplateAttribute");

                            b1.WithOwner()
                                .HasForeignKey("UserTemplate_tid");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
