// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using auth_server.Repositories;

namespace auth_server.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200705151226_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("auth_server.Models.CountryModels.Country", b =>
                {
                    b.Property<Guid>("_cid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("_cid");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("auth_server.Models.OrganizationModels.Organization", b =>
                {
                    b.Property<Guid>("_oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("_templateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("_oid");

                    b.HasIndex("_templateId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("auth_server.Models.OrganizationModels.UserTemplate", b =>
                {
                    b.Property<Guid>("_tid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("_tid");

                    b.ToTable("UserTemplates");
                });

            modelBuilder.Entity("auth_server.Models.OrganizationModels.Organization", b =>
                {
                    b.HasOne("auth_server.Models.OrganizationModels.UserTemplate", null)
                        .WithMany()
                        .HasForeignKey("_templateId");
                });
#pragma warning restore 612, 618
        }
    }
}
