// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using auth_server.Repositories;

namespace auth_server.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200706074927_AddedOwnedProperties")]
    partial class AddedOwnedProperties
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("auth_server.Models.CountryModels.Country", b =>
                {
                    b.Property<Guid>("_cid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_cid");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("auth_server.Models.OrganizationModels.Organization", b =>
                {
                    b.Property<Guid>("_oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("_templateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("_oid");

                    b.HasIndex("_templateId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("auth_server.Models.UserTemplateModels.UserTemplate", b =>
                {
                    b.Property<Guid>("_tid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("_tid");

                    b.ToTable("UserTemplates");
                });

            modelBuilder.Entity("auth_server.Models.CountryModels.Country", b =>
                {
                    b.OwnsMany("auth_server.Models.CountryModels.State", "_states", b1 =>
                        {
                            b1.Property<Guid>("Country_cid")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.HasKey("Country_cid", "Id");

                            b1.ToTable("State");

                            b1.WithOwner()
                                .HasForeignKey("Country_cid");
                        });
                });

            modelBuilder.Entity("auth_server.Models.OrganizationModels.Organization", b =>
                {
                    b.HasOne("auth_server.Models.UserTemplateModels.UserTemplate", null)
                        .WithMany()
                        .HasForeignKey("_templateId");

                    b.OwnsOne("auth_server.Models.OrganizationModels.Address", "_address", b1 =>
                        {
                            b1.Property<Guid>("Organization_oid")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Organization_oid");

                            b1.ToTable("Organizations");

                            b1.WithOwner()
                                .HasForeignKey("Organization_oid");
                        });
                });

            modelBuilder.Entity("auth_server.Models.UserTemplateModels.UserTemplate", b =>
                {
                    b.OwnsMany("auth_server.Models.UserTemplateModels.UserTemplateAttribute", "_attributes", b1 =>
                        {
                            b1.Property<Guid>("UserTemplate_tid")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("_name")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("_type")
                                .HasColumnType("int");

                            b1.HasKey("UserTemplate_tid", "Id");

                            b1.ToTable("UserTemplateAttribute");

                            b1.WithOwner()
                                .HasForeignKey("UserTemplate_tid");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
